### ISSUE TITLE
Bug  util.lua

### ISSUE THREAD

**Issue by albicasty** [mrastegari/XNOR-Net#5]
Hi,
I noticed you modified the util.lua file, adding  m:add(1/(n)):mul(1-1/s[2])**:mul(n)** in the updateBinaryGradWeight function. However, I don't get which is the origin of this modification and where in your paper you talk about it. Moreover, I am training  a binarized version of the resnet: the problem is the training diverges with the mul(n).

In addition, may you also upload the model you used for training the binarized Resnet?
Thank you.

**Comment by mrastegari** [comment]
please see the discussion at https://github.com/mrastegari/XNOR-Net/issues/3You may use the provided function in the discussion for ResNet. Since I have made changes in the code I need to re train the ResNet again. I will upload it once I am done.

**Comment by albicasty** [comment]
Thank you!

I am trying to reproduce you results with the ResNet 18. However, for the first epochs the Top5 and Top1 values are much lower that the ones you declared. For this reason, I think I have not modified properly their model.
